.TH BRN2 1 "2023-03-25" "1.0" "brn2 man page"

.SH NAME
brn2 - Command-line tool for renaming multiple files at once.

.SH SYNOPSIS
.B brn2
[\fIfiles.txt\fR]

.SH DESCRIPTION
.B brn2
opens a buffer in your default text editor with the list of filenames in the current directory or the filenames specified in a text file. You can edit the filenames in the buffer, and the changes will be applied when you save and exit.

If given one argument, it is interpreted as the text filename with a list of filenames to rename. You can then edit the filenames in the buffer, and the changes will take place when you save and exit.

By default, it uses $EDITOR, and if that is not set, then $VISUAL.

Note that it will not work for filenames longer than PATHMAX characters and newlines in filenames are also not allowed.

.SH OPTIONS
None.

.SH EXIT STATUS
The program returns 0 if successful, and a non-zero value if an error occurs.

.SH EXAMPLES
To rename files in the current directory, simply run:
.P
.BR brn2
.P
To rename files specified in a text file, run:
.P
.BR brn2 
files.txt
.P
where files.txt contains the list of filenames to rename.

.SH AUTHOR
Written by Lucas Mior.

.SH COPYRIGHT
Copyright 2023 Lucas Mior.

.SH SEE ALSO
rename(1), sed(1), mv(1)
