.TH BRN2 1

.SH NAME
brn2 \- Bulk Rename Files

.SH SYNOPSIS
brn2 [OPTIONS] -f <filename>
.TP
brn2 [OPTIONS] -- [<file1> <file2> ... ]

.SH DESCRIPTION
brn2 is a command line tool to easily mass-rename files in your preferred text
editor (e.g., vim). It will open the filenames in your text editor of choice.
You can then edit the filenames in the buffer, and the changes will take place
when you save and exit.

.SH OPTIONS
.TP
.BR -h
.BR --help
Display the help message and exit.

.TP
.BR -q
.BR --quiet
Quiet mode; suppress output messages.

.TP
.BR -v
.BR --verbose
Verbose mode; output messages (this is the default).

.TP
.BR -c
.BR --check
Check if original filenames exist before renaming.

.SH USAGE
.TP
.BR brn2
Rename filenames in the current working directory.

.TP
.BR brn2 " -f <filename>"
Rename filenames listed in the specified file.

.TP
.BR brn2 " <file1> <file2> ..."
Rename filenames passed as arguments.

.SH NOTES
.TP
By default, brn2 uses the $EDITOR environment variable. If that is not set, it defaults to vim.

.TP
.brn2 will not work for more than 2^32 renames at once.

.TP
.brn2 will not work for filenames longer than PATH_MAX (typically 4096)
characters when reading from <filename>. Newlines in filenames are not allowed.

.TP
Filenames listed in <filename> or given as arguments that do not correspond to existing files will generate errors while renaming.

.TP
Filenames . and .. are ignored, as well as any filename that starts with .. even
when listed in <filename>

.SH CHANGES OVER ORIGINAL BRN
.TP
Option to rename files listed in a file given as the first argument

.TP
Option to rename files passed as arguments

.TP
It prints renamed files

.TP
Faster algorithm to check for duplicated filenames

.SH EXIT STATUS
.BR 1
if an error ocurred,
.BR 0
otherwise.

.SH LICENSE
.brn2 is licensed under the GNU AFFERO GENERAL PUBLIC LICENSE.
