complete -c brn2 -s h -d 'Display help and exit.'
complete -c brn2 -l help -d 'Display this help message and exit.'
complete -c brn2 -s q -d 'Quiet mode; suppress output messages.'
complete -c brn2 -l quiet -d 'Quiet mode; suppress output messages.'
complete -c brn2 -s v -d 'Verbose mode (default); output messages.'
complete -c brn2 -l verbose -d 'Verbose mode (default); output messages.'
complete -c brn2 -s c -d 'Check if original file names exist.'
complete -c brn2 -l check -d 'Check if original file names exist.'
complete -c brn2 -s s -d 'Disable sorting of original list.'
complete -c brn2 -l sort -d 'Disable sorting of original list.'
complete -c brn2 -s F -d 'Exit on first renaming error.'
complete -c brn2 -l fatal -d 'Exit on first renaming error.'
complete -c brn2 -s i -d 'Rename files not given in the list of files to rename.'
complete -c brn2 -l implict -d 'Rename files not given in the list of files to rename.'
complete -c brn2 -s e -d 'Only rename files given in the list of files to rename (default).'
complete -c brn2 -l explict -d 'Only rename files given in the list of files to rename (default).'
