name: FreeBSD CI

on:
  push:
    branches:
  pull_request:

jobs:
  build:
    runs-on: freebsd-14-64
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: cc --version

      - name: Build and Test
        run: ./build.sh test
