name: Test on various platforms CI

on:
  push:
    branches:
  pull_request:

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: |
          xcode-select --install 2>/dev/null || true
          cc --version

      - name: Build and Test
        run: ./build.sh test
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build deps
        run: cc --version

      - name: Build and Test
        run: ./build.sh test
